version: '2'
services:
    joyas-app:
        image: joyas
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://joyas-mysql:3306/joyas?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    joyas-mysql:
        extends:
            file: mysql.yml
            service: joyas-mysql
